// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebPartDashboard.Data;

#nullable disable

namespace WebPartDashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260321192905_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebPartDashboard.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("Status");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = "Разработчик",
                            CreatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Реализовать CRUD функционал для управления задачами",
                            DueDate = new DateTime(2024, 1, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCompleted = false,
                            Priority = 2,
                            Status = 1,
                            Title = "Создать веб-часть для задач"
                        },
                        new
                        {
                            Id = 2,
                            AssignedTo = "Администратор",
                            CreatedAt = new DateTime(2024, 1, 13, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Установить и настроить подключение к PostgreSQL",
                            DueDate = new DateTime(2024, 1, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCompleted = true,
                            Priority = 1,
                            Status = 3,
                            Title = "Настроить базу данных PostgreSQL"
                        },
                        new
                        {
                            Id = 3,
                            AssignedTo = "Тестировщик",
                            CreatedAt = new DateTime(2024, 1, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Провести тестирование всех CRUD операций",
                            DueDate = new DateTime(2024, 1, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCompleted = false,
                            Priority = 1,
                            Status = 0,
                            Title = "Протестировать CRUD операции"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
